# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('AuthSer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('origin_filename', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom_files', to='chat.ChatRoomMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom_files', to='AuthSer.User')),
            ],
        ),
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('origin_filename', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_files', to='chat.TopicMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_files', to='AuthSer.User')),
            ],
        ),
    ]
